"""Build the study library's generated subjects: jet engine, heart, car engine.

Each becomes dashboard/static/models/<id>.glb.gz (geometry, one named node
per component) and data/assemblies/<id>.json (the component list, what each
part does, how it connects, sources, and how it separates). The geometry is
original and generated here from code (numpy only): nothing is downloaded.
Output is deterministic. Any geometry change must bump that subject's
geometry_revision, because saved studies pin the manifest.

    python scripts/build_study_models.py
"""
import gzip
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / 'study_models'))

from study_geometry import rot, to_glb, vertex_count  # noqa: E402
import car_engine  # noqa: E402
import heart  # noqa: E402
import jet_engine  # noqa: E402

DRAFTED = ('Explanations drafted by Apex from the listed general references; not yet reviewed by an '
           'engineer or clinician.')

SUBJECTS = {}


def subject(**kw):
    SUBJECTS[kw['id']] = kw


subject(
    id='jet-engine', module=jet_engine, mirror_x=True, explode_scale=(1.6, 1.1, 1.0), order=10, category='Engineering',
    title='Turbofan jet engine', subtitle='High-bypass turbofan · component study',
    summary='How an airliner engine turns air and fuel into thrust: fan, compressors, combustor, turbines and shafts.',
    fidelity='Illustrative model · not to scale',
    limitations=('An original teaching model generated from code, not manufacturer CAD. Blade counts, stage counts, '
                 'clearances and proportions are simplified and not to scale. The casings are cut away so the core '
                 'is visible. Spool motion shows which parts turn together; it is not a flow or thermal simulation. '
                 + DRAFTED),
    validation={'purpose': 'Learning how a turbofan works, part by part',
                'geometry': 'Original illustrative geometry generated by scripts/build_study_models.py',
                'dimensions': 'Not to scale; no real engine dimensions',
                'materials': 'Colours suggest typical materials only (titanium fan, nickel-alloy turbine)',
                'physics': 'No aerodynamic, thermal or structural simulation; motion is illustrative',
                'review': 'Explanations AI-drafted from general references; independent review pending'},
    sources=[{'id': 'nasa', 'title': 'NASA Glenn Research Center · Turbofan engine', 'url': 'https://www.grc.nasa.gov/www/k-12/airplane/aturbf.html'},
             {'id': 'turbofan', 'title': 'Turbofan · Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Turbofan'},
             {'id': 'combustor', 'title': 'Combustor · Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Combustor'},
             {'id': 'turbine', 'title': 'Turbine blade · Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Turbine_blade'}],
    text={
        'spinner': ('Smooths air into the fan and sheds ice and debris away from the blade roots.',
                    'Bolted to the front of the fan hub; turns with the fan and the low-pressure spool.', 'turbofan'),
        'fan': ('The big front rotor. In a high-bypass engine most of the thrust comes from air the fan pushes around the core, not through it.',
                'Driven by the low-pressure turbine through the low-pressure shaft. Its air splits: most goes down the bypass duct, some into the core.', 'nasa'),
        'fan-case': ('A strong ring around the fan that would contain a released blade.',
                     'Mounted inside the nacelle, close around the fan-blade tips; that tight gap keeps the fan efficient.', 'turbofan'),
        'nacelle': ('The aerodynamic outer cowling: it shapes the inlet, lines the bypass duct and forms the fan nozzle at the back.',
                    'Surrounds the fan case and bypass duct; in service it hinges open for maintenance and carries the thrust reverser.', 'turbofan'),
        'ogv': ('Stationary vanes behind the fan that straighten the swirling bypass air so it produces thrust instead of spin.',
                'Span the bypass duct between the core cowl and the outer duct wall, just downstream of the fan.', 'turbofan'),
        'core-cowl': ('The smooth inner wall of the bypass duct. Its sharp front edge, the splitter, divides fan air between bypass and core.',
                      'Wraps the whole core, from just behind the fan to the core nozzle.', 'turbofan'),
        'lpc': ('The booster: a few stages that begin squeezing the air entering the core.',
                'On the low-pressure spool with the fan, so it turns at fan speed.', 'nasa'),
        'hpc': ('Many stages of small blades that squeeze the core air to a small fraction of its volume before it burns.',
                'On the high-pressure spool, driven by the high-pressure turbine at a much higher speed than the fan.', 'nasa'),
        'compressor-case': ('Holds the stationary stator vanes between the rotating compressor stages; each stator row turns the flow to feed the next rotor.',
                            'Encloses both compressors and ties the fan frame to the combustor casing.', 'nasa'),
        'combustor': ('The ring-shaped chamber where fuel burns continuously in the compressed air, raising its temperature enormously.',
                      'Takes air from the high-pressure compressor and feeds the hot gas straight into the high-pressure turbine.', 'combustor'),
        'fuel-nozzles': ('Spray finely atomised fuel into the combustor so it mixes and burns quickly and evenly.',
                         'A fuel manifold ring feeds each nozzle through the combustor casing.', 'combustor'),
        'core-case': ('The pressure vessel around the combustor and turbines.',
                      'Bolts to the compressor casing in front and carries the turbine vanes and exhaust hardware.', 'nasa'),
        'hpt': ('The first turbine: extracts energy from the hottest gas to drive the high-pressure compressor. Its blades are internally cooled.',
                'Directly behind the combustor, joined to the high-pressure compressor by the high-pressure shaft.', 'turbine'),
        'turbine-vanes': ('Stationary vanes that accelerate and aim the hot gas onto each row of turbine blades.',
                          'Alternate with the rotating turbine stages, held by the turbine casing.', 'turbine'),
        'lpt': ('Several stages that take the remaining energy from the gas to drive the fan and booster.',
                'Behind the high-pressure turbine; joined to the fan by the low-pressure shaft running through the middle of the engine.', 'nasa'),
        'core-nozzle': ('Accelerates the core exhaust rearward for the last part of the thrust.',
                        'At the end of the core, inside the fan stream.', 'nasa'),
        'exhaust-plug': ('Shapes the core exhaust as it leaves the engine.',
                         'Fixed to the turbine exhaust frame at the centre of the core nozzle.', 'turbofan'),
        'lp-shaft': ('The inner shaft: carries power from the low-pressure turbine forward to the fan.',
                     'Runs inside the hollow high-pressure shaft; the two spools turn independently at different speeds.', 'turbofan'),
        'hp-shaft': ('The outer, hollow shaft joining the high-pressure turbine to the high-pressure compressor.',
                     'Concentric around the low-pressure shaft.', 'turbofan'),
        'gearbox': ('Drives the fuel pump, oil pump and generators, and receives the starter to spin the engine up.',
                    'A tower shaft takes power off the high-pressure spool down to the gearbox.', 'turbofan'),
    },
    notes={'fan': '22 blades shown; real counts vary by engine.', 'hpc': '9 stages shown.', 'lpt': '5 stages shown.',
           'nacelle': 'Cut away so the fan and core stay visible.', 'core-cowl': 'Cut away so the core stays visible.',
           'compressor-case': 'Cut away; stator rows shown between rotor stages.', 'core-case': 'Cut away so the combustor and turbines are visible.'},
)

subject(
    id='heart', module=heart, mirror_x=False, turn_y=0.72, explode_scale=(1.15, 1.15, 1.15), order=20, category='Biology',
    title='Human heart', subtitle='Chambers, valves, vessels & wiring · anatomy study',
    summary='The four chambers, four valves, great vessels, coronary arteries and electrical conduction system.',
    fidelity='Illustrative anatomy · not to scale',
    limitations=('An original, simplified teaching model generated from code, not from medical imaging. Shapes, '
                 'wall thickness and proportions are approximate; chambers are shown as solid forms rather than '
                 'hollow muscle, and small vessels, cardiac veins and trabeculae are omitted. Colours follow the '
                 'teaching convention (blue for oxygen-poor blood). Not for diagnosis or clinical use. ' + DRAFTED),
    validation={'purpose': 'Learning cardiac anatomy and the path of blood',
                'geometry': 'Original illustrative geometry generated by scripts/build_study_models.py',
                'dimensions': 'Not to scale; no patient or atlas measurements',
                'materials': 'Teaching colours only',
                'physics': 'No blood-flow, pressure or electrophysiology simulation',
                'review': 'Explanations AI-drafted from general references; clinical review pending'},
    sources=[{'id': 'nhlbi', 'title': 'NHLBI (NIH) · How the heart works', 'url': 'https://www.nhlbi.nih.gov/health/heart'},
             {'id': 'heart', 'title': 'Heart · Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Heart'},
             {'id': 'valves', 'title': 'Heart valve · Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Heart_valve'},
             {'id': 'coronary', 'title': 'Coronary arteries · Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Coronary_arteries'},
             {'id': 'conduction', 'title': 'Electrical conduction system of the heart · Wikipedia',
              'url': 'https://en.wikipedia.org/wiki/Electrical_conduction_system_of_the_heart'}],
    text={
        'left-ventricle': ('The main pumping chamber: its thick wall pushes oxygen-rich blood out through the aorta to the whole body.',
                           'Fills from the left atrium through the mitral valve; empties through the aortic valve. Forms the apex, the pointed tip.', 'nhlbi'),
        'right-ventricle': ('Pumps oxygen-poor blood to the lungs. It needs far less pressure than the left, so its wall is thinner.',
                            'Fills from the right atrium through the tricuspid valve; empties through the pulmonary valve into the pulmonary trunk.', 'nhlbi'),
        'right-atrium': ('Receives oxygen-poor blood returning from the body.',
                         'Fed by the superior and inferior venae cavae; passes blood to the right ventricle. Home of the sinoatrial node, the natural pacemaker.', 'nhlbi'),
        'left-atrium': ('Receives oxygen-rich blood returning from the lungs.',
                        'Fed by the four pulmonary veins; passes blood to the left ventricle through the mitral valve.', 'nhlbi'),
        'septum': ('The muscular wall between the ventricles, keeping oxygen-rich and oxygen-poor blood apart.',
                   'Shared by both ventricles; the conduction bundle branches run down each side of it.', 'heart'),
        'aorta': ('The largest artery: carries oxygen-rich blood from the left ventricle to the body.',
                  'Rises from the aortic valve, arches over the pulmonary arteries, gives off the head and arm arteries, and descends behind the heart.', 'heart'),
        'pulmonary-trunk': ('Carries oxygen-poor blood from the right ventricle to the lungs. The only arteries that carry oxygen-poor blood.',
                            'Splits into the left and right pulmonary arteries, the right one passing under the aortic arch.', 'heart'),
        'superior-vena-cava': ('Returns oxygen-poor blood from the head, neck and arms.',
                               'Enters the top of the right atrium.', 'heart'),
        'inferior-vena-cava': ('Returns oxygen-poor blood from the lower body.',
                               'Enters the bottom of the right atrium.', 'heart'),
        'pulmonary-veins': ('Bring oxygen-rich blood back from the lungs, two from each lung.',
                            'Enter the back of the left atrium.', 'heart'),
        'tricuspid-valve': ('Three leaflets that let blood pass from the right atrium into the right ventricle and stop it flowing back.',
                            'Tethered by chordae tendineae to papillary muscles in the ventricle, which stop the leaflets turning inside out.', 'valves'),
        'mitral-valve': ('Two leaflets between the left atrium and left ventricle; closes when the ventricle contracts.',
                         'Tethered by chordae tendineae to papillary muscles in the left ventricle.', 'valves'),
        'aortic-valve': ('Three pocket-like cusps at the exit of the left ventricle that stop blood falling back from the aorta.',
                         'At the root of the aorta; the coronary arteries branch off just above it.', 'valves'),
        'pulmonary-valve': ('Three cusps at the exit of the right ventricle that stop blood falling back from the pulmonary trunk.',
                            'At the root of the pulmonary trunk.', 'valves'),
        'coronary-arteries': ("The heart muscle's own blood supply. A blockage here causes a heart attack.",
                              'Branch from the base of the aorta and run in the grooves on the surface: left anterior descending, circumflex and right coronary artery.', 'coronary'),
        'conduction-system': ('The electrical wiring that times each beat: SA node, AV node, bundle of His and bundle branches.',
                              'Starts at the SA node in the right atrium, pauses at the AV node, then runs down the septum to spread through both ventricles.', 'conduction'),
    },
    notes={'left-ventricle': 'Shown as a solid form; real ventricles are hollow with thick muscular walls.',
           'right-ventricle': 'Shown as a solid form wrapped against the left ventricle.',
           'coronary-arteries': 'Main branches only.', 'conduction-system': 'Shown glowing and simplified; really microscopic tissue within the walls.',
           'tricuspid-valve': 'Leaflets and chordae simplified.', 'mitral-valve': 'Leaflets and chordae simplified.'},
)

subject(
    id='car-engine', module=car_engine, mirror_x=False, explode_scale=(1.0, 0.85, 1.0), order=30, category='Engineering',
    title='Car engine (inline-four)', subtitle='Four-stroke petrol engine · DOHC 16-valve',
    summary='How a car engine makes power: block, pistons, crankshaft, head, valves, camshafts, timing and ignition.',
    fidelity='Illustrative model · not to scale',
    limitations=('An original teaching model generated from code, not manufacturer CAD. Proportions, clearances, '
                 'ports and cooling passages are simplified; the block is cut open so the pistons show. Moving '
                 'parts are shown at one instant (pistons 1 and 4 at the top). No combustion, flow or load '
                 'simulation. ' + DRAFTED),
    validation={'purpose': 'Learning how a four-stroke engine works, part by part',
                'geometry': 'Original illustrative geometry generated by scripts/build_study_models.py',
                'dimensions': 'Not to scale; no real engine dimensions',
                'materials': 'Colours suggest typical materials only',
                'physics': 'No combustion, thermal or load simulation',
                'review': 'Explanations AI-drafted from general references; independent review pending'},
    sources=[{'id': 'four-stroke', 'title': 'Four-stroke engine · Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Four-stroke_engine'},
             {'id': 'inline-four', 'title': 'Inline-four engine · Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Inline-four_engine'},
             {'id': 'valvetrain', 'title': 'Valvetrain · Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Valvetrain'},
             {'id': 'crankshaft', 'title': 'Crankshaft · Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Crankshaft'},
             {'id': 'timing', 'title': 'Timing belt · Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Timing_belt_(camshaft)'}],
    text={
        'block': ('The backbone: holds the four cylinders the pistons slide in, and the crankshaft bearings below. Coolant passages run through it.',
                  'The head bolts on top, the oil pan underneath, the timing drive on the front and the flywheel on the back.', 'inline-four'),
        'main-caps': ('Clamp the crankshaft into the block at each main journal, around oil-fed plain bearings.',
                      'Bolted to the block bulkheads underneath the crankshaft.', 'crankshaft'),
        'crankshaft': ('Turns the up-and-down push of the pistons into rotation. Counterweights balance the offset crankpins.',
                       'Connecting rods ride on its crankpins; it drives the flywheel at the back and the timing belt and pulleys at the front.', 'crankshaft'),
        'rods': ('Link each piston to the crankshaft, turning straight-line motion into rotation.',
                 'Small end on the piston (wrist) pin; big end bolted around a crankpin.', 'crankshaft'),
        'piston-1': ('Seals the cylinder and takes the push of the burning mixture. Rings seal gas above and scrape oil below.',
                     'Rides in cylinder 1 on a wrist pin and connecting rod. Pistons 1 and 4 move together; shown at the top.', 'four-stroke'),
        'piston-2': ('Seals the cylinder and takes the push of the burning mixture.',
                     'Rides in cylinder 2. Pistons 2 and 3 move together; shown at the bottom.', 'four-stroke'),
        'piston-3': ('Seals the cylinder and takes the push of the burning mixture.',
                     'Rides in cylinder 3. Pistons 2 and 3 move together; shown at the bottom.', 'four-stroke'),
        'piston-4': ('Seals the cylinder and takes the push of the burning mixture.',
                     'Rides in cylinder 4. Pistons 1 and 4 move together; shown at the top.', 'four-stroke'),
        'head-gasket': ('Seals the joint between block and head against combustion pressure, coolant and oil.',
                        'Clamped between the block deck and the cylinder head.', 'inline-four'),
        'cylinder-head': ('Closes the top of each cylinder to form the combustion chamber, and carries the ports, valves and camshafts.',
                          'Bolted on the block; intake manifold on one side, exhaust on the other.', 'four-stroke'),
        'valves': ('Open and close the ports: intake valves let air and fuel in, exhaust valves let burnt gas out. Springs snap them shut.',
                   'Four per cylinder, pushed open by the camshaft lobes through the bucket tappets.', 'valvetrain'),
        'camshafts': ('Egg-shaped lobes open each valve at exactly the right moment. One shaft works the intake valves, the other the exhaust.',
                      'Driven by the timing belt at half crankshaft speed, since each valve opens once every two turns.', 'valvetrain'),
        'valve-cover': ('Closes the top of the head and keeps the valvetrain oil in.', 'Bolted to the cylinder head.', 'valvetrain'),
        'ignition': ('The coils make a high-voltage pulse; the spark plugs fire it across a gap to ignite the mixture near the top of the compression stroke.',
                     'One coil sits on each plug, and each plug screws into the head at the centre of its combustion chamber.', 'four-stroke'),
        'intake-manifold': ('Brings air to each cylinder. The throttle body at its inlet controls how much air, and so how much power.',
                            'Bolted to the intake ports on one side of the head.', 'four-stroke'),
        'exhaust-manifold': ('Collects hot exhaust from each cylinder and merges it into one pipe towards the catalytic converter.',
                             'Bolted to the exhaust ports on the other side of the head.', 'four-stroke'),
        'timing-belt': ('Keeps the camshafts in step with the crankshaft so the valves never meet the pistons.',
                        'A toothed belt from the crankshaft sprocket around both cam sprockets, the tensioner and here the water pump.', 'timing'),
        'accessory-drive': ('A separate belt from the crankshaft pulley that drives the alternator (electricity) and other accessories.',
                            'On the front of the crankshaft, ahead of the timing belt.', 'inline-four'),
        'flywheel': ('A heavy disc that smooths out the pulses of the power strokes; its ring gear lets the starter motor turn the engine.',
                     'Bolted to the back of the crankshaft; the clutch and gearbox attach to it.', 'crankshaft'),
        'oil-pan': ('Holds the engine oil at the bottom of the engine, where the pump draws it up.', 'Bolted under the block.', 'inline-four'),
        'oil-filter': ('Cleans the oil of wear particles before it reaches the bearings.', 'Screws onto the side of the block in the oil circuit.', 'inline-four'),
    },
    notes={'block': 'Cut open at the front so the pistons show.', 'valves': '16 valves with springs and bucket tappets.',
           'camshafts': 'Lobe timing follows firing order 1-3-4-2.'},
)


def orientation(spec):
    """Orient a subject for the study's default camera: mirror and/or turn about the vertical."""
    R = np.diag([-1.0, 1.0, 1.0]) if spec['mirror_x'] else np.eye(3)
    if spec.get('turn_y'):
        R = rot((0, 1, 0), spec['turn_y']) @ R
    return R


def render(spec):
    """(parts, motion, glb bytes) for one subject."""
    parts, motion = spec['module'].build()
    return parts, motion, to_glb(parts, spec['module'].MATERIALS, spec['title'], orientation(spec))


def build(spec):
    parts, motion, glb = render(spec)
    R = orientation(spec)
    k3 = np.asarray(spec.get('explode_scale', (1, 1, 1)), float)
    ids = [p.id for p in parts]
    assert len(ids) == len(set(ids)) and set(ids) == set(spec['text']), (spec['id'], set(ids) ^ set(spec['text']))
    (ROOT / 'dashboard/static/models' / f"{spec['id']}.glb.gz").write_bytes(gzip.compress(glb, 9, mtime=0))
    rows = []
    for k, p in enumerate(parts):
        purpose, connection, source = spec['text'][p.id]
        rows.append({'id': p.id, 'node': k, 'name': p.name, 'group': p.group, 'purpose': purpose, 'connection': connection,
                     'model_note': spec['notes'].get(p.id, 'Illustrative shape, simplified for teaching.'), 'source': source,
                     'explode': [round(float(v), 4) for v in R @ (np.asarray(p.explode, float) * k3)]})
    manifest = {'id': spec['id'], 'revision': '1.0', 'geometry_revision': '1', 'title': spec['title'],
                'subtitle': spec['subtitle'], 'category': spec['category'], 'order': spec['order'], 'summary': spec['summary'],
                'fidelity': spec['fidelity'], 'caption': spec['fidelity'] + ' · AI-drafted notes',
                'asset': f"/api/study/model/{spec['id']}/asset", 'asset_file': f"{spec['id']}.glb.gz",
                'validation': spec['validation'], 'limitations': spec['limitations'], 'sources': spec['sources'], 'parts': rows}
    if motion:
        manifest['motion'] = dict(motion, axis=[round(float(v), 6) + 0.0 for v in R @ np.asarray(motion['axis'], float)],
                                  pivot=[round(float(v), 6) + 0.0 for v in R @ np.asarray(motion['pivot'], float)])
    (ROOT / 'data/assemblies' / f"{spec['id']}.json").write_text(json.dumps(manifest, indent=1, ensure_ascii=False) + '\n')
    return len(parts), vertex_count(parts), len(glb)


if __name__ == '__main__':
    for spec in SUBJECTS.values():
        n, verts, size = build(spec)
        print(f"{spec['id']}: {n} components, {verts:,} vertices, {size / 1e6:.1f} MB glb")
