const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../dashboard/static/study-diagnostics.js'),'utf8');
const Metrics=new Function(source.replace('export class','class').replace('export function','function')+';return StudyDiagnostics;')();
const m=new Metrics();
m.frame(0);m.event('grabs');assert.equal(m.report(10),null,'collection must be opt-in');
m.start('dc-motor',0);m.frame(0);m.frame(16);m.frame(32);m.frame(40,false);m.frame(10000);m.frame(10016);
assert.deepEqual(m.report(10020).frame_interval_ms,{samples:3,median:16,p95:16},'hidden time is excluded');
const sample={tracking:true,age_ms:12,sequence:1,hands:[{x:.2,y:.8}],token:'secret',notes:'private'};
m.sample(sample,30);m.sample(sample,40,true);
m.sample({...sample,age_ms:500},50);m.sample({...sample,age_ms:500},60);
m.sample({...sample,sequence:2},70);m.sample({...sample,age_ms:null},80);
assert.equal(m.report().counts.fresh_frames,2,'repeated detector frames are not new frames');
assert.equal(m.report().counts.stale_episodes,2,'stale episodes count transitions');
assert.equal(m.report().counts.blocked_samples,1);
assert.equal(m.report().detector_sample_age_ms.samples,5,'unknown age is not zero');
const data=m.data;m.event('grabs');m.event('applied');m.stop(11000);
const stopped=m.report(20000);m.frame(22000);m.event('grabs');assert.deepEqual(m.report(30000),stopped,'stopped reports stay frozen');
m.start('openmotor-125',30000);m.event('applied',data);assert.equal(m.report().counts.applied,0,'old in-flight actions cannot enter a new recording');
for(let n=0;n<1000;n++)m.sample({...sample,sequence:n},n);
const r=m.report(31000);assert.equal(r.hand_request_round_trip_ms.samples,600,'timing memory is bounded');
assert.equal(r.counts.samples,1000,'counts cover the whole recording');
const json=JSON.stringify(r);for(const secret of ['secret','private','hands','token','notes'])assert(!json.includes(secret),'no sensitive sample fields exported');
console.log('PASS: opt-in diagnostics, bounded windows, hidden-time exclusion, stale episodes, privacy, frozen reports and recording isolation.');
