const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<button id="camera-mirror-toggle"></button><figure id="camera-mirror" hidden><img id="camera-mirror-image"><figcaption id="camera-mirror-status"></figcaption></figure>',{url:'https://apex.example/study',runScripts:'outside-only'});
const w=dom.window,$=id=>w.document.getElementById(id),requests=[],revoked=[],timers=new Map();let id=0,blobs=0,hidden=false;
w.AbortController=AbortController;w.URL.createObjectURL=()=>`blob:test-${++blobs}`;w.URL.revokeObjectURL=u=>revoked.push(u);
w.setTimeout=(fn,delay)=>{timers.set(++id,{fn,delay});return id;};w.clearTimeout=id=>timers.delete(id);
Object.defineProperty(w.document,'hidden',{get:()=>hidden});
w.fetch=(url,opts)=>new Promise((resolve,reject)=>requests.push({url,opts,resolve,reject}));
w.eval(fs.readFileSync('dashboard/static/study-mirror.js','utf8').replace('export function','function')+';setupStudyMirror({token:()=>"test-token"});');
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
const response=()=>({ok:true,blob:async()=>new Blob(['jpeg'],{type:'image/jpeg'})});
(async()=>{
 assert.equal(requests.length,0,'off by default makes no camera request');
 $('camera-mirror-toggle').click();assert.equal(requests.length,1);assert.equal($('camera-mirror').hidden,false);
 assert.equal(requests[0].url,'/api/study/camera');assert.equal(requests[0].opts.headers.Authorization,'Bearer test-token');assert.equal(requests[0].opts.cache,'no-store');
 requests[0].resolve(response());await flush();assert.equal($('camera-mirror-image').getAttribute('src'),'blob:test-1');
 assert.equal(timers.size,1,'one next poll, never a concurrent queue');
 const [tid,t]=timers.entries().next().value;timers.delete(tid);t.fn();assert.equal(requests.length,2);
 $('camera-mirror-toggle').click();assert.equal($('camera-mirror').hidden,true);assert(requests[1].opts.signal.aborted);
 assert.equal($('camera-mirror-image').getAttribute('src'),null);assert.deepEqual(revoked,['blob:test-1']);
 requests[1].resolve(response());await flush();assert.equal(timers.size,0);assert.equal(blobs,1,'late response cannot restore a hidden preview');
 $('camera-mirror-toggle').click();hidden=true;w.document.dispatchEvent(new w.Event('visibilitychange'));
 assert(requests[2].opts.signal.aborted);requests[2].reject(Error('cancelled'));await flush();assert.equal(timers.size,0);
 hidden=false;w.document.dispatchEvent(new w.Event('visibilitychange'));assert.equal(requests.length,4);
 requests[3].resolve({ok:false,json:async()=>({detail:'Camera unavailable'})});await flush();assert.equal($('camera-mirror-status').textContent,'Camera unavailable');
 assert.equal($('camera-mirror-image').getAttribute('src'),null);
 w.dispatchEvent(new w.Event('pagehide'));assert.equal(timers.size,0);
 assert(requests.every(r=>!r.opts.method),'preview never changes camera settings or gesture ownership');
 console.log('PASS: opt-in authenticated mirror, decode lifecycle, bounded polling, hide/abort/cleanup, tab suspension, and no gesture writes.');w.close();
})().catch(e=>{console.error(e);process.exitCode=1;w.close();});
