"""Write-approval gate — stage memory/note/skill writes for the user to approve.

When config.MEMORY_WRITE_APPROVAL (or SKILL_WRITE_APPROVAL) is True, mutating
calls are parked in the staged_writes table and a push notification is sent
instead of being applied immediately. The user approves or rejects from the
dashboard (or via the approve/reject helpers), at which point the write is
applied with the approval gate bypassed.

Mirrors the cortex pending_actions pattern so the dashboard UX is consistent.
"""
import json
import time
from typing import Callable, Optional

from agent import longterm

_notify_fn: Optional[Callable] = None


def set_notify_fn(fn: Callable) -> None:
    global _notify_fn
    _notify_fn = fn


def init_db() -> None:
    with longterm._conn() as c:
        c.execute("""
            CREATE TABLE IF NOT EXISTS staged_writes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                ts REAL NOT NULL,
                kind TEXT NOT NULL,          -- memory | note | skill
                summary TEXT NOT NULL,       -- human-readable one-liner
                payload_json TEXT NOT NULL,  -- args needed to apply the write
                status TEXT NOT NULL DEFAULT 'pending'
            )
        """)


def _summarize(kind: str, payload: dict) -> str:
    if kind == "memory":
        return f"{payload.get('action')} -> {payload.get('target')}: {str(payload.get('content'))[:80]}"
    if kind == "note":
        return f"note '{payload.get('title')}' in {payload.get('folder', 'Notes')}"
    if kind == "skill":
        return f"skill '{payload.get('name')}': {str(payload.get('description'))[:80]}"
    if kind == "email":
        return f"email to {payload.get('to')}: {str(payload.get('subject'))[:80]}"
    if kind == "skill_code":
        return (f"REWRITE executable skill {payload.get('name')!r} — "
                f"{len(payload.get('code', ''))} chars generated by "
                f"{payload.get('trigger', '?')}")
    if kind == "goal_proposal":
        # The evidence rides in the summary because that is what reaches the
        # push notification. A proposal you cannot audit from the notification
        # is one you will rubber-stamp or ignore.
        return f"{payload.get('title')} — {payload.get('evidence', 'no evidence')}"
    return kind


def stage(kind: str, payload: dict) -> str:
    """Park a write for approval. Returns a message telling the agent it's queued."""
    # Ensure the table exists. Staging is now the gate for autonomously-written
    # executable code, so a missing table must not be the reason a rewrite
    # silently fails to be reviewed.
    try:
        init_db()
    except Exception:
        pass
    summary = _summarize(kind, payload)
    with longterm._conn() as c:
        cur = c.execute(
            "INSERT INTO staged_writes (ts, kind, summary, payload_json, status) "
            "VALUES (?, ?, ?, ?, 'pending')",
            (time.time(), kind, summary, json.dumps(payload)),
        )
        write_id = cur.lastrowid
    if _notify_fn:
        try:
            _notify_fn(
                title="Apex wants to save something",
                body=f"[{kind}] {summary}",
                kind="write_approval",
            )
        except Exception:
            pass
    return (
        f"[STAGED for approval #{write_id}] {kind} write held pending review "
        f"(approval gate is on). The user will approve or reject it from the dashboard."
    )


def list_pending(status: str = "pending") -> list[dict]:
    try:
        with longterm._conn() as c:
            rows = c.execute(
                "SELECT id, ts, kind, summary, payload_json, status "
                "FROM staged_writes WHERE status = ? ORDER BY ts DESC LIMIT 50",
                (status,),
            ).fetchall()
    except Exception:
        return []
    return [
        {"id": r[0], "ts": r[1], "kind": r[2], "summary": r[3],
         "payload": json.loads(r[4]), "status": r[5]}
        for r in rows
    ]


def _apply(kind: str, payload: dict) -> str:
    """Apply a previously staged write, bypassing the approval gate."""
    if kind == "memory":
        return longterm.save_memory_entry(
            target=payload["target"], action=payload["action"],
            content=payload.get("content"), old_text=payload.get("old_text"),
            _bypass_approval=True,
        )
    if kind == "note":
        from agent import vault
        return vault.write_note(
            payload["title"], payload.get("content", ""),
            folder=payload.get("folder", "Notes"),
            tags=payload.get("tags"), links=payload.get("links"),
            _bypass_approval=True,
        )
    if kind == "skill":
        from agent import skill_md
        return skill_md.manage(
            "create", name=payload.get("name"),
            description=payload.get("description"), content=payload.get("content"),
            _bypass_approval=True,
        )
    if kind == "email":
        from tools import email_box
        return email_box.send(
            payload["to"], payload.get("subject", ""), payload.get("body", ""),
            in_reply_to=payload.get("in_reply_to"),
        )
    if kind == "skill_code":
        # The only path by which an autonomously-rewritten executable skill
        # reaches disk. _trigger="manual" bypasses staging entirely, so this
        # runs exclusively for code a model wrote and a human approved.
        from agent import skills as _skills
        return _skills.create_skill(
            payload["name"], payload.get("description", ""), payload["code"],
            version=payload.get("version", "1.0"),
            # Provenance is preserved, not laundered: the rewrite stays
            # attributed to whatever generated it, so rollback and audit can
            # still tell model-written code from hand-written code. Only the
            # gate is bypassed, because this IS the approval.
            _trigger=payload.get("trigger", "manual"), _bypass_approval=True,
        )

    if kind == "goal_proposal":
        # THE gate for agent-originated goals. agent/initiative.py only ever
        # stages; this line is the sole path from a proposal to a real goal, and
        # it runs when the user approves. Structural, not a prompt instruction.
        from agent import goals
        return goals.set_goal(
            payload["title"], payload.get("description", ""),
            horizon=payload.get("horizon", "week"),
        )
    return f"Unknown staged kind: {kind!r}"


def approve(write_id) -> str:
    """Approve one staged write, or 'all' to approve every pending write."""
    if str(write_id).lower() == "all":
        results = []
        for w in list_pending("pending"):
            results.append(approve(w["id"]))
        return f"Approved {len(results)} write(s)." if results else "Nothing pending."

    # Atomically CLAIM the row before applying, so two concurrent approvals
    # (e.g. approve(id) racing approve("all")) can't both fire the side effect.
    with longterm._conn() as c:
        cur = c.execute(
            "UPDATE staged_writes SET status = 'approving' WHERE id = ? AND status = 'pending'",
            (int(write_id),),
        )
        if cur.rowcount != 1:
            return f"Staged write #{write_id} not found or already processed."
        row = c.execute(
            "SELECT kind, payload_json FROM staged_writes WHERE id = ?",
            (int(write_id),),
        ).fetchone()
    kind, payload_json = row
    try:
        result = _apply(kind, json.loads(payload_json))
    except Exception as e:
        # Don't leave the row stuck in 'approving' — release it back to pending so
        # it stays visible/re-approvable instead of vanishing from the queue.
        with longterm._conn() as c:
            c.execute("UPDATE staged_writes SET status = 'pending' WHERE id = ?", (int(write_id),))
        return f"Apply failed for #{write_id}, returned to pending: {e}"
    with longterm._conn() as c:
        c.execute("UPDATE staged_writes SET status = 'approved' WHERE id = ?", (int(write_id),))
    return f"Approved #{write_id}: {result}"


def _remember_declines(rows) -> None:
    """Tell initiative that these subjects were rejected.

    Without this, declining a proposed goal means "raise it again in six hours",
    which trains the user to stop reading proposals — and a review gate nobody
    reads is worse than none, because it still looks like oversight.
    """
    try:
        from agent import initiative
        for (payload_json,) in rows:
            key = json.loads(payload_json or "{}").get("evidence_key")
            if key:
                initiative.decline(key)
    except Exception as e:
        print(f"[Approvals] could not record decline: {e}")


def reject(write_id) -> str:
    """Reject one staged write, or 'all' to reject every pending write."""
    if str(write_id).lower() == "all":
        with longterm._conn() as c:
            rows = c.execute(
                "SELECT payload_json FROM staged_writes "
                "WHERE status = 'pending' AND kind = 'goal_proposal'").fetchall()
            c.execute("UPDATE staged_writes SET status = 'rejected' WHERE status = 'pending'")
        _remember_declines(rows)
        return "Rejected all pending writes."
    with longterm._conn() as c:
        rows = c.execute(
            "SELECT payload_json FROM staged_writes WHERE id = ? AND kind = 'goal_proposal'",
            (int(write_id),)).fetchall()
        c.execute("UPDATE staged_writes SET status = 'rejected' WHERE id = ?", (int(write_id),))
    _remember_declines(rows)
    return f"Staged write #{write_id} rejected."
